.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. noirshares_qt test_noirshares_qt
clean: FORCE
	$(MAKE) -C .. noirshares_qt_clean test_noirshares_qt_clean
check: FORCE
	$(MAKE) -C .. test_noirshares_qt_check
noirshares-qt noirshares-qt.exe: FORCE
	 $(MAKE) -C .. noirshares_qt
